<a href="https://colab.research.google.com/github/sammaknshinde2410/Data-Analytics/blob/main/DAAssignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
np.__config__

<module 'numpy.__config__' from '/usr/local/lib/python3.10/dist-packages/numpy/__config__.py'>

In [ ]:
# 2. Write a NumPy program to get help on the add function.
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

In [ ]:
#3. Write a NumPy program to test whether none of the elements of a given array is zero.
a= np.array([0,1,2,4,5,6])
np.all(a)

False

In [ ]:
# 4. Write a NumPy program to test whether any of the elements of a given array is non-zero.
b = np.array([1,2,4,5,6])
np.any(a)

True

In [ ]:
# 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).
c = np.array([1, 0, np.nan, np.inf])
np.isfinite(c)

array([ True,  True, False, False])

In [ ]:
# 6. Write a NumPy program to test element-wise for positive or negative infinity.
d = np.array([1, 0, np.nan, np.inf])
np.isinf(d)

array([False, False, False,  True])

In [ ]:
# 7. Write a NumPy program to test element-wise for NaN of a given array.
e = np.array([1, 0, np.nan, np.inf])
np.isnan(e)

array([False, False,  True, False])

In [ ]:
#8 Write a NumPy program to test element-wise for complex number, real number of a given array. Alsotest whether a given number is a scalar type or not.
d = np.array([23,23+4j,4,5,23+4j])
print(np.iscomplex(d))
print(np.isscalar(45))
print(np.isreal(d))


[False  True False False  True]
True
[ True False  True  True False]


In [ ]:
# 9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and
# less_equal) of two given arrays.
print(np.less_equal(np.array([1,3,5]),np.array([2,1,6])))
print(np.array([1,3,5])<np.array([2,1,6]))
print(np.array([1,3,5])==np.array([2,1,6]))

[ True False  True]
[ True False  True]
[False False False]


In [ ]:
#10 Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
arr1 = np.array([1,7,13,105])
arr1.nbytes

32

In [ ]:
#11 Write a NumPy program to create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#11 Write a NumPy program to create an array of 10 ones.
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#11 Write a NumPy program to create an array of 10 fives.
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
#12 Write a NumPy program to create an array of the integers from 30 to70.
arr2 = np.arange(30,71)
arr2

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [ ]:
#13 Write a NumPy program to create an array of all the even integers from 30 to 70.
arr2 = np.arange(30,71,2)
arr2

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [ ]:
# 14. Write a NumPy program to create a 3x3 identity matrix.
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 15. Write a NumPy program to generate a random number between 0 and 1.
arr=np.random.rand(1)
arr

array([0.13481486])

In [ ]:
# 16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
arr=np.random.randn(15)
arr

array([-0.66962671,  3.35589537,  0.19040751,  0.83359149, -0.36031488,
        0.79618022,  1.73956261,  0.30089636, -0.75742567, -0.6679874 ,
        0.70166355, -0.12055064,  1.86504689, -0.58827864, -0.57517882])

In [ ]:
#17 Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
arr = np.arange(15,56)
arr[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [ ]:
# 18. Write a NumPy program to create a 3X4 array.
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#19. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
arr3 = np.arange(5,51,5)
arr3

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
# 20. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
arr=np.arange(0,21)
arr[9:16]=arr[9:16]*-1
arr

In [ ]:
# 21. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
np.random.randint(0,10,size=5)


array([2, 8, 8, 0, 6])

In [ ]:
# 22. Write a NumPy program to multiply the values of two given vectors.
np.random.randint(0,10,size=5)*np.random.randint(0,100,size=5)

array([588, 819, 584,  10, 144])

In [ ]:
# 23. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
np.random.randint(10,21,size=12).reshape(3,4)

array([[15, 20, 13, 15],
       [14, 14, 18, 18],
       [18, 16, 17, 15]])

In [ ]:
# 24. Write a NumPy program to find the number of rows and columns of a given matrix.
np.random.randint(10,21,size=12).reshape(3,4).shape

(3, 4)

In [ ]:
# 25. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 26. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be
# equal to 1, and inside 0.
arr=np.random.randint(1,2,size=100).reshape(10,10)
arr[1:-1,1:-1]=0
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
# 27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
# 3, 4, 5.
arr=[1,2,3,4,5,6]
np.diag(arr)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [ ]:
# 28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
np.random.randint(1,100,size=27).reshape((3,3,3))

array([[[21, 56, 66],
        [43, 20, 23],
        [57, 17, 12]],

       [[37, 90, 31],
        [61, 40,  5],
        [54, 23, 20]],

       [[19, 44, 55],
        [12,  6, 32],
        [14, 63, 72]]])

In [ ]:
# 29. Write a NumPy program to compute the inner product of two given vectors.
arr1=np.random.randint(0,100,size=5)
arr2=np.random.randint(0,100,size=5)
np.inner(arr1,arr2)

9503

In [ ]:
# 30. Write a NumPy program to sort a given array by row and column in ascending order.
armali=np.random.randint(1,100,size=27).reshape((3,3,3))
print(np.sort(armali,axis=0))
print(np.sort(armali))

[[[11 79  9]
  [47 11 10]
  [13 83  5]]

 [[39 83 30]
  [57 13 17]
  [64 92 61]]

 [[66 93 39]
  [97 72 44]
  [66 99 96]]]
[[[39 66 93]
  [13 44 47]
  [61 66 83]]

 [[ 9 39 83]
  [10 57 72]
  [64 92 96]]

 [[11 30 79]
  [11 17 97]
  [ 5 13 99]]]


In [ ]:
# 31. Write a NumPy program to extract all numbers from a given array which are less and greater
# than a specified number.
print(arr1)
print(arr1[arr1>5])
print(arr1[arr1<5])

[55  1  8 74 61]
[55  8 74 61]
[1]


In [ ]:
# 32. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a
# given number.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
given_number = 5
arr[arr == given_number] = 0
arr[arr < given_number] = -1
arr[arr > given_number] = 1
arr

array([-1, -1, -1, -1, -1,  1,  1,  1,  1])

In [ ]:
# 33. Write a NumPy program to create an array of equal shape and data type of a given array.
chagan=np.empty_like(arr1)
chagan

array([1, 2, 4, 5, 6])

In [ ]:
# 34. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.
np.random.randint(1,100,size=60).reshape((3,5,4))

In [ ]:
# 35. Write a NumPy program to multiply two given arrays of same size element-by-element.
a=np.arange(1,5)
b=np.arange(1,5)
np.multiply(a,b)

array([ 1,  4,  9, 16])

In [ ]:
np.linspace(0,100,num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])